FROM nvcr.io/nvidia/pytorch:24.07-py3

# Install system dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    libasound2-dev \
    portaudio19-dev \
    build-essential \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project metadata and lock file
COPY pyproject.toml ./

# Install dependencies
RUN pip install --upgrade pip \
&& pip install .

COPY . .

# Make port 8000 available
EXPOSE 8000

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]